
remove(predictions)
remove(test)
remove(test_d)
remove(test_d1)
remove(test_data)
remove(test_data1)
remove(test_data3)
remove(train)
remove(train_d)
remove(train_d1)
remove(train_data)
remove(train_data3)

remove(x)
remove(y)
remove(z)
remove(k)
remove(rmse)
remove(str)
remove(temp1)

remove(neural_network)
remove(formula)
remove(train_indices)


remove(train_index)
remove(tree)
remove(tree1)
remove(tree3)

remove(dat.d)
remove(test_d_l)
remove(train_d_l)
remove(test.loan)
remove(test.loan)
remove(knnModel)
remove(testData)
remove(train.loan)
remove(trainData)



remove(accuracy)
remove(accuracy1)
remove(accuracy3)
remove(confusion_matrix)
remove(confusion_matrix1)
remove(predictions)
remove(predictions1)
remove(predictions3)
remove(t_id)
remove(t_id1)
remove(train_index)
remove(train_index1)
remove(train3)
remove(train_data1)
remove(trainIndex)

remove(svm_model1)
remove(svm_model2)
remove(svm_model)


remove(p2)
remove(temp)
remove(testval_d)
remove(val_d)
remove(pred)
remove(r)
remove(t2_id)

remove(f1)
remove(precision)
remove(recall)

remove(rf_model)
remove(i)
remove(pred1)
remove(predt)

remove(price_parts)
remove(subset_list)
remove(model)

remove(actual_values)
remove(columns_to_normalize)
remove(mse)
remove(rain_indices)
remove(predicted_outcomes)
remove(predicted_outcomes)


remove(ctrl)
remove(confMatrix)
remove(newData)

remove(input_data)
remove(g1)
remove(binary_predictions)
